require:
 - rubocop-rake
 - rubocop-rspec

AllCops:
  SuggestExtensions: false
  NewCops: enable

Metrics/MethodLength:
  Enabled: false

Layout/LineLength:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/CommentedKeyword:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Layout/FirstHashElementIndentation:
  Enabled: false