FROM swaffy/cloud-template-base

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock Rakefile .rubocop.yml .rspec serverless.yml ./
RUN bundle install

COPY lib/ lib/
COPY spec/ spec/

CMD bunlde exec rake