FROM swaffy/cloud-template-base

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG SLS_ACCESS_KEY_ID
ARG SLS_SECRET_ACCESS_KEY
ARG BRANCH

ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV BRANCH ${BRANCH}

RUN sls config credentials \
  --provider aws \
  --key ${SLS_ACCESS_KEY_ID} \
  --secret ${SLS_SECRET_ACCESS_KEY}

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock Rakefile serverless.yml ./
RUN bundle install

COPY lib/ lib/

RUN bundle exec rake deploy_dev

CMD sls