FROM swaffy/cloud-template-base

ARG AWS_ACCESS_KEY_ID
ARG AWS_SECRET_ACCESS_KEY
ARG BRANCH

ENV AWS_ACCESS_KEY_ID ${AWS_ACCESS_KEY_ID}
ENV AWS_SECRET_ACCESS_KEY ${AWS_SECRET_ACCESS_KEY}
ENV BRANCH ${BRANCH}

RUN mkdir -p /app
WORKDIR /app

COPY Gemfile Gemfile.lock Rakefile .rubocop.yml .rspec serverless.yml ./
RUN bundle install

COPY lib/ lib/
COPY spec/ spec/
COPY coverage/ coverage/

CMD bunlde exec rake