# frozen_string_literal: true

source 'https://rubygems.org'

gem 'chronic_duration', '~> 0.10.6'
gem 'sinatra'
gem 'puma'
gem 'fileutils'
gem 'json'
gem 'optimist'
gem 'rake'
gem 'rspec'
gem 'rubocop'
gem 'rubocop-performance'
gem 'rubocop-rake'
gem 'rubocop-rspec'
gem 'simplecov'
gem 'mail'
gem 'httparty'
gem 'mongo'
gem 'logger'
gem 'debase'
gem 'ruby-debug-ide'
gem 'pry'
