---
service: cloud-template
provider:
  name: aws
  runtime: ruby2.7
  profile: serverlessUser
  stage: dev-CT-13
  region: ap-southeast-2
custom:
  databaseUrl: mongodb+srv://swaff-y:UVY3bBAVir4lFkYu@subscribers.91iwg.mongodb.net/cloud_template
  apiKeys:
  - name: devKey
functions:
  api_status:
    handler: lib/lambda/handler.api_status
    environment:
      DATABASE_URL: "${self:custom.databaseUrl}"
    events:
    - http:
        path: status
        method: GET
        cors: true
        private: true
