service: $APPLICATION

provider:
  name: aws
  runtime: ruby2.7
  profile: default
  stage: $STAGE
  region: ap-southeast-2

plugins:
  - serverless-add-api-key

custom:
  databaseUrl: $DATABASE_URL
  apiKeys:
    - name: devKey

functions:
  api_status:
    handler: lib/lambda/handler.api_status
    environment:
      DATABASE_URL: ${self:custom.databaseUrl}
    events:
      - http: 
            path: status
            method: GET
            cors: true
            private: true