service: $APPLICATION

provider:
  name: aws
  runtime: ruby2.7
  profile: default
  stage: $STAGE
  region: ap-southeast-2

plugins:
  - serverless-add-api-key

custom:
  databaseUrl: $DATABASE_URL
  apiKeys:
    - name: devKey

functions:
  api_status:
    image:
      name: cloud-template-lambda
        path: ./
      command:
        - lib/lambda/handler.api_status
      entryPoint:
        - '/lambda-entrypoint.sh'
      events:
        - httpApi:
            path: /status
            method: get