

steps:
  - label: ":package: Build, Package and run tests"
    commands:
      - "mkdir -p /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}"
      - "mkdir -p /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}"
      - "cp ./serverless.yml /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml"
      - "export AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')"
      - "sh .buildkite/scripts/build_and_test.sh"
    agents:
      queue: default
    artifact_paths:
      - "/Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml"

  - wait: ~
    continue_on_failure: false

  - block: ':computer: Deploy stack?'

  - name: ':desert_island: Deploy'
    commands:
      - "rm serverless.yml"
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml" .'
      - "cp Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml ."
      - "npm install"
      - "bundle install --without development test"
      - "bundle exec rake aws_login"
      - 'sls deploy'
    agents:
      queue: default

  - wait

  - block: ':hammer: Remove Stack'

  - name: ':package: Removing stack'
    commands: 
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml" .'
      - "cp Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml ."
      - "npm install"
      - 'sls remove'
    agents:
      queue: default
