steps:
  - label: ":package: Build, Package and run tests"
    commands:
      - "mkdir -p /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}"
      - "mkdir -p /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}"
      - "cp ./serverless.yml /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml"
      - "cp ./postman_collection.json /Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/postman_collection.json"
      - "export AWS_ACCOUNT=$(aws sts get-caller-identity | jq -r '.Account')"
      - "sh .buildkite/scripts/build_and_test.sh"
    agents:
      queue: default
    artifact_paths:
      - "/Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml"
      - "/Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/postman_collection.json"

  - wait: ~
    continue_on_failure: false

  - block: ':computer: Deploy stack?'

  - name: ':desert_island: Deploy'
    commands:
      - "rm serverless.yml"
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml" .'
      - "cp Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml ."
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/postman_collection.json" .'
      - "cp Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/postman_collection.json ."
      - "npm install"
      - "bundle install --without development test"
      - "bundle exec rake aws_login"
      - 'sls deploy > deploy_result'
      - 'cat deploy_result'
    agents:
      queue: default
    artifact_paths:
      - "deploy_result"
      - "/Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/postman_collection.json"

  - wait

  - name: ':postman: postman'
    commands:
      - "rm postman_collection.json"
      - 'buildkite-agent artifact download "deploy_result" .'
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/postman_collection.json" .'
      - "bundle install --without development test"
      - 'sh .buildkite/scripts/postman.sh'
    agents:
      queue: default
    artifact_paths:
      - "postman_result"

  - wait

  - block: ':hammer: Remove Stack'

  - name: ':package: Removing stack'
    commands: 
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml" .'
      - "cp Users/kyleswaffield/docker/${BUILDKITE_PIPELINE_NAME}/${BUILDKITE_BRANCH}/serverless.yml ."
      - "npm install"
      - 'sls remove'
    agents:
      queue: default
