steps:
  - label: ":package: Build, Package and run tests"
    command: "sh .buildkite/scripts/build_and_test.sh"
    agents:
    - "queue=default"
  - label: ":popcorn: Start deployment"
    command: "pwd"
    agents:
    - "queue=default"
