steps:
  - label: ":package: Build, Package and run tests"
    command: "sh .buildkite/scripts/build_and_test.sh"
    agents:
    - "queue=default"

  - wait

  - label: ":popcorn: Start deployment"
    command: "sh .buildkite/scripts/deployment.sh"
    agents:
    - "queue=default"
