

steps:
  - label: ":package: Build, Package and run tests"
    commands:
      - "env"
      - "cp ./serverless.yml /Users/kyleswaffield/docker/serverless.yml"
      - "sh .buildkite/scripts/build_and_test.sh"
    agents:
      queue: default
    artifact_paths:
      - "/Users/kyleswaffield/docker/serverless.yml"

  - wait

  - name: ':desert_island: Deploy'
    commands:
      - "rm serverless.yml"
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/serverless.yml" .'
      - "cp Users/kyleswaffield/docker/serverless.yml ."
      - "npm install"
      - 'sls deploy'
    agents:
      queue: default

  - wait

  - block: ':hammer: Remove Stack'

  - name: ':package: Removing stack'
    commands: 
      - 'buildkite-agent artifact download "Users/kyleswaffield/docker/serverless.yml" .'
      - "cp Users/kyleswaffield/docker/serverless.yml ."
      - "npm install"
      - 'sls remove'
    agents:
      queue: default
